### ISSUE TITLE
Epic: Revise SRT stats API

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1215]
Revise SRT stats API.

- [ ] Revise and improve `CBytePerfmon` structure.

- [ ] Revise, improve and add missing statistics:

- [ ] Update the documentation: #1207.

**Comment by OdaDaisuke** [comment]
Hi, Let me help this issue.
These roadmaps are in progress?

**Comment by mbakholdina** [comment]
Hi @OdaDaisuke, thank you for offering your help. Many statistics related improvements and issues need to be addressed carefully as they require API changes. We postponed major improvements to 1.5.1 release. If any help will be required, I'll let you know.

**Comment by Fanfwe** [comment]
Hi @mbakholdina
Since 1.5.1 has now been released and does not include any of this, do you have a new target for this issue ?

**Comment by maxsharabayko** [comment]
Hi @Fanfwe 
Will see. Might be included in v1.6.0 if time permits.

**Comment by maxsharabayko** [comment]
A table of currently present/missing stats

![image](https://github.com/Haivision/srt/assets/12700120/e32e4ed0-7549-496c-bbe8-092ef3d95205)
