### ISSUE TITLE
Roadmap: Features and Regression for planned 1.5.0

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#1493]
1. Group support

- [x] Creating a group and use it as socket
- [x] Using socket API that is intended OR NOT to work with groups
- [x] Listener accepting or rejecting a group-member connection
- [x] Sending and receiving via group, disallowed for single sockets
- [x] Epoll report connect-ready for a group
- [x] Epoll reporting connection error for a group
- [x] Epoll and update reported on group connection

2. Cross-features

- [x] Listener callback cooperation with groups
- [x] Test caller/sender + listener/receiver for backup groups
- [x] Test caller/receiver + listener/sender for backup groups
- [x] Both above for a case when connections are accepted over different listeners
