### ISSUE TITLE
[apps] Use ISO 8601 / RFC 3339 datetime format for Timepoint

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1618]
As of v1.4.2 `srt-live-transmit` write the absolute timepoint in a non-standard format:
```
01.01.1900 00:00:00.199725 +0100
```
The format is parsed by python (pandas), but other languages/libraries may have difficulties.
See [this comment](https://github.com/Haivision/srt/pull/1489#issuecomment-713176380) in #1489.

Use ISO 8601 / RFC 3339 datetime format.

```
1900-01-01 00:00:00.199725+0100
```

There is some uncertainty around using a space character as the separator instead of `T`.
Using `T` reduces the readability, so I would vote for a space, but some further study is needed.

[Section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6) Internet Date/Time Format of RFC 3339 says:

> NOTE: ISO 8601 defines date and time separated by "T". Applications using this syntax may choose, for the sake of readability, to specify a full-date and full-time separated by (say) a space character.

### TODO

- [ ] Decide on using a space character instead of `T` as the date and time separator.

- [ ] When must `Z` be used?

- [ ] No (space) separator before the timezone (+0100)?
