### ISSUE TITLE
[Epic] Socket Groups - v1.4.2 Issues (Broadcast)

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1622]
This ticket is created to track issues introduced by socket groups functionality in v1.4.2.
Broadcast mode only.

#### Critical

- [x] #1631 - Recusrive lock on closing a group.
- [x] #1625 - SIGSEGV while attempting group connect to SRT 1.3.2 peer. **Status: investigating.**
- [x] #1605 - deadlock upon group connection. **Status: not longer seen after certain fixes.**
- [x] #1603 - Broken sockets accumulate in group data. **Fix ready. Awaiting PR.**
- [x] #1612 - No EPOLL_ERR notification on broken group socket async receiver. **Fix ready. Awaiting PR.**

#### Medium

- [x] #1599 - SIGSEGV upon failed link in non-blocking backup group caller/sender. **Workaround exists. Not reproducible with the fix for 1603**
- [x] #1585 - SIGABRT when calling srt_strerror from connect callback function. **Workaround: log error number instead of a string.**

- [ ] #1575 - sequence discrepancy. **Reason: unknown. Fix attempt failed.** Reported by @ethouris based on his tests.

#### Low Priority

- [x] #1591 - SRT_MSGCTRL documentation

### Fixed

- [x] #1608 - Crash when reconnecting a group

**Comment by jeandube** [comment]
I am pretty sure [#1605](https://github.com/Haivision/srt/issues/1605) is fixed in @ethouris branch I am testing. I think the fix is simple and worth a merge to ease QA testing, or at least an updated status in this epic.

**Comment by maxsharabayko** [comment]
Issue #1575 is the only one remaining.
This Epic can be closed, as #1575 was only observed in testing, and will be handled separately.
