### ISSUE TITLE
[Docs] Improve README

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1779]
## TODO

- [x] Maria to reorganize `docs` folder and rename the files appropriately. See PR #1911.
- [ ] Consider [the audit for SRT GitHub repo](https://maintainer.io/) in general.
- [x] Maria to rework Guides section so that we have the draft for Documentation and Contributing sections.
   - [x] Add the link to SRT Deployment Guide, now we only have the link to SRT Technical Overview.
- [x] Maria to prepare a draft of Getting Started section. Build Instructions section remain as is for now.
- [x] Maxim to improve Requirements section.

- [x] Steve to improve the Introduction section so that it briefly describes the protocol, it's main goals and major features. I guess we can take some text from the [RFC introductory sections](https://haivision.github.io/srt-rfc/draft-sharabayko-mops-srt.html#name-secure-reliable-transport-p).

   It's important to have the direct link to the latest valid RFC from the introduction as well as mentioning the SRT alliance behind the project. I like how it's done in ["What is SRT?"](https://broadcastfocus.com/2020/08/13/what-is-srt/) article at broadcastfocus.com:
   
   > Secure, Reliable Transport, known simply as SRT, is a protocol that allows unreliable networks like the internet to be used for reliable, encrypted, live video contribution. Created by Haivision and now an open-source technology with an IETF draft spec, the alliance of SRT users continues to grow as the technology continues to develop and add features. 
   
   We should also list the major features of SRT at the end of the Introduction section.

- [x] Improve README formatting and decide on what sections are missing as per [Steve's suggestion](https://github.com/stevomatthews/srt/blob/master/README.md).
   
- [x] Move Build Instructions in a separate document.
   - [ ] Steve to improve Build Instructions formatting.

## Proposed Structure

Proposed Structure:
- Introduction (What is SRT? or (General) Overview)
- Getting Started
   - Requirements
   - Build Instructions (with a link to a separate document)
   - Sample Applications (srt-live-transmit, srt-xtransmit, etc.)
   - Tools (at list 3 of Maria's scripts: srt-stats-plotting, lib-tcpdump-processing, lib-srt-utils)
- Documentation 
- Contributing

## Examples

- https://obsproject.com/wiki/Streaming-With-SRT-Protocol

**Comment by stevomatthews** [comment]
Some resources:
[**Awesome README**](https://github.com/matiassingers/awesome-readme/blob/master/readme.md) – Examples, articles and tools
[**Make a README**](https://www.makeareadme.com/) – ReadMe 101, template, best practices
[**Maintainer.io**](https://maintainer.io/) – Open source project maintenance service (free audits)

**Comment by stevomatthews** [comment]
Steve's working copy of SRT README:
https://github.com/stevomatthews/srt/blob/master/README.md

**Comment by stevomatthews** [comment]
Also started looking at organizing the /docs folder:

**Comment by stevomatthews** [comment]
**[The Essential Sections for Better Documentation of Your README Project]**(https://www.welcometothejungle.com/en/articles/btc-readme-documentation-best-practices)
Some good guidelines and links to examples/tools
