### ISSUE TITLE
[BUG] FEC packet filter config

### ISSUE THREAD

**Issue by alex-prykhodko** [Haivision/srt#1808]
**Test Environment :**

Use `srt-live-transmit` to setup two connecting peers as follows.

Sender with FEC:
`srt-live-transmit udp://239.10.36.10:5000 srt://10.129.10.53:5001?latency=500&packetfilter=fec,cols:20,rows:10`

Receiver without FEC :
`srt-live-transmit srt://:5001?latency=500 udp://239.10.36.10:5010`

Receiver with FEC :
`srt-live-transmit srt://:5001?latency=500&packetfilter=fec,cols:10 udp://239.10.36.10:5010`

**Observed Issues :**

1. Connection is established even if the receiver does not have packet filter configured.

2. FEC packet filter config returned via SRTO_PACKETFILTER socket option is not updated after connection is established. E.g. with the commands above, receiver config returned is always "fec,cols:10" (configured value) while the sender is using different config.

3. FEC packet filter requires that at least cols value is set on receiver side. Expected behavior - to be able to configure receiver as "fec" without any additional values (*this configuration should also work with a sender that has FEC disabled*).

**Comment by ethouris** [comment]
Ok, my first takealook: yes, the filter need not be set to be overridden by other side that has set the filter. Likely this was a requirement that we haven't properly documented. In the meantime there has been a misunderstanding as to how to configure the filter - that is, what would happen when both sides simply set `fec`. In this case none of them specifies the parameters and therefore the connection should be somehow rejected. The current version goes simplest way and doesn't allow "fec" to be set as an option at all.

We need to change this, but then we need to agree about the new requirements, that is:

1. "fec"  <--> "fec" - rejected: none of the parties specified parameters
2. "fec" <---> "fec,cols:10,rows:20" - accepted: both sides use the configuration with cols:10 and rows:20
3. "fec,cols:10" <--> "fec,cols:10,rows:20" - rejected: both specified parameters and they differ
4. "fec,cols:10" <--> "fec,cols:10" - accepted: both configuration specs are the same
5. Setting the SRTO_PACKETFILTER option can only be rejected if you specify an unsupported filter type.

Is that ok?

**Comment by ethouris** [comment]
#1811 should fix some of the found problems.

The matter of allowing or not allowing FEC configuration (adaptive vs. no-filter) is to be solved separately.

**Comment by maxsharabayko** [comment]
Notes after the sync up. Intersecting with the original description on some parts.

### TODO

- [ ] `SRTO_PACKETFILTER` must return the full config after connection is established, including default values (e.g. rows=1).
- [ ] Check case sensitivity, e.g. "FEC" vs "fec". A lower case is preferable, but only if it is the current behavior. Document the current behavior.
- [ ] Add filter negitiation matrix to the documentation (e.g. FEC,cols10 <--> FEC,cols11 -> rejection SRT_REJFILTER).
- [ ] Fix connection when filter parameters collide: cols:10 vs cols:11. PR #1811.

**Comment by ethouris** [comment]
The last 2 points are theoretically fulfilled, but light way - it is simply explained that parameters that are specified on both sides and with different values are rejected. The documentation mentions 3 cases when configuration comparison and integration may result in rejection.
