### ISSUE TITLE
CUDTUnited::m_GlobControlLock takes too much responsibility

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#2393]
It looks like the `CUDTUnited::m_GlobControlLock` has to protect:
- `CUDTUnited::m_Sockets`,
- `CUDTUnited::m_Groups`,
- `CUDTUnited::m_PeerRec`,
- `CUDTUnited::m_ClosedSockets,
- `CUDTUnited::m_ClosedGroups`.

It also occasionally protects
- `CUDTUnited::m_mMultiplexer`, although there is a dedicated `m_mMultiplexerLock`. See `CUDTUnited::updateListenerMux(..)`.
- WTF `CUDTUnited::bind()` locks `CUDTSocket::m_ControlLock`?

### TODO

- [ ] Define the scope of the `CUDTUnited::m_GlobControlLock` mutex.
- [ ] Clean up the use of the  `CUDTUnited::m_GlobControlLock` mutex.
- [ ] Update the low level info document.

**Comment by gou4shi1** [comment]
related issue https://github.com/Haivision/srt/issues/2252
