### ISSUE TITLE
Remove old receiver buffer implementation

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#2407]
The new receiver buffer implementation was introduced in v1.5.0.
However, the old implementation is still available and can be enabled using the `ENABLE_NEW_RCVBUFFER=OFF` build option.
It is a fallback solution in case some critical issue around the new implementation arises after the release.

The old implementation can be removed in the future major release.
This would also allow changing the type of the `CUnit::m_iFlag` to bool, as the new receiver buffer tracks the state by itself.

### TODO

- [ ] Remove the old `CRcvBuffer` implementation.
- [ ] Remove the `ENABLE_NEW_RCVBUFFER` build option.
- [ ] Potentially change `CUnit::m_iFlag` to `bool`.
