### ISSUE TITLE
Make it possible to set nul character in StreamID using the URI

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#3039]
To be able to test issue #2284 resolved by PR #2845 there is a need for two more items:

- [x] Add a related unit test checking handling of a NUL character. PR #3040.

- [x] Make it possible to set a NUL character via URI. URI parser supports percent decoding after PR #2015, but %00 is not handled properly. <br/> Fixed in PR #3041.

- [x] Modify srt-xtransmit to print StreamID with percent decoding in mind. PR https://github.com/maxsharabayko/srt-xtransmit/pull/99.
- [x] Report an isue to Wireshark to properly show StreamID value with a NUL character inside. https://gitlab.com/wireshark/wireshark/-/issues/20113
